prowjob_namespace: default
pod_namespace: test-pods

plank:
  default_decoration_configs:
    "*":
      utility_images:
        clonerefs: "gcr.io/k8s-prow/clonerefs:v20191108-08fbf64ac"
        initupload: "gcr.io/k8s-prow/initupload:v20191108-08fbf64ac"
        entrypoint: "gcr.io/k8s-prow/entrypoint:v20191108-08fbf64ac"
        sidecar: "gcr.io/k8s-prow/sidecar:v20191108-08fbf64ac"
      gcs_configuration:
        bucket: prow-test-bucket
        path_strategy: explicit
      gcs_credentials_secret: gcs-credentials

postsubmits:
  moomin123/testrepo:
  - name: branch-filter-master
    decorate: true        
    spec:
      containers:
      - image: python:3
        command:
        - sh
        - -c 
        - |
          git status
          git log -3
          cat README.md
          sleep 15
    branches:
    - ^master$

  - name: semver-publish-python
    decorate: true        
    spec:
      volumes:
      - name: pypirc
        secret:
          secretName: pypirc
      containers:
      - image: python:3
        volumeMounts:
        - name: pypirc 
          mountPath: /root/.pypirc
          subPath: .pypirc
          readOnly: true
        command:
        - sh
        - -c 
        - scripts/publish_python_library.sh
    branches:
    # Filter on tags with semantic versioning, prefixed with "v"
    # https://github.com/semver/semver/issues/232
    - ^v(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(-(0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(\.(0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*)?(\+[0-9a-zA-Z-]+(\.[0-9a-zA-Z-]+)*)?$

  - name: semver-publish-docker
    decorate: true        
    spec:
      volumes:
      - name: pypirc
        secret:
          secretName: pypirc
      containers:
      - image: python:3
        volumeMounts:
        - name: pypirc 
          mountPath: /root/.pypirc
          subPath: .pypirc
          readOnly: true
        command: scripts/publish_docker_images.sh
    branches:
    # Filter on tags with semantic versioning, prefixed with "v"
    # https://github.com/semver/semver/issues/232
    - ^v(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(-(0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(\.(0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*)?(\+[0-9a-zA-Z-]+(\.[0-9a-zA-Z-]+)*)?$