apiVersion: v1
kind: Pod
metadata:
  name: testpod
  labels:
    env: test
spec:
  volumes:
  - name: docker-socket
    hostPath:
      path: /var/run/docker.sock
  containers:
  - name: testpod
    image: google/cloud-sdk:273.0.0
    volumeMounts:
    - name: docker-socket
      mountPath: /var/run/docker.sock
    securityContext:
      privileged: true
    command:
    - tail 
    - -f 
    - /dev/null
